FROM php:$VERSIONTAG

RUN mkdir -p /app

# Set working directory
WORKDIR /app

COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/

RUN chmod +x /usr/local/bin/install-php-extensions \
    && sync \
    && install-php-extensions @composer gd pdo_mysql mysqli zip exif \
    && rm -rf /var/cache/apk/*


# Copy existing application directory contents
RUN chown -R www-data:www-data /app/
USER www-data

# Expose port 9000 and start php-fpm server
EXPOSE 9000
ENTRYPOINT ["php-fpm"]
