FROM php:8.1.8-fpm-alpine

RUN mkdir -p /app

# Set working directory
WORKDIR /app

COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/

RUN chmod +x /usr/local/bin/install-php-extensions \
    && sync \
    && apk add --update linux-headers \
    && install-php-extensions @composer xdebug gd pdo_mysql mysqli zip exif \
    && rm -rf /var/cache/apk/*


# Expose port 9000 and start php-fpm server
EXPOSE 9000
ENTRYPOINT ["php-fpm"]
