version: "3"

services:
  app:
    build: .
    ports:
      - "8080:8080"
  sut:
    image: alpine:3.13
    depends_on:
      - app
    command: /tmp/run_tests.sh
    volumes:
      - "./run_tests.sh:/tmp/run_tests.sh:ro"
