name: Build docker php-fpm-composer

on:
  schedule:
    - cron: "0 2 1 * *" # At 02:00 on day-of-month 1.
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  IMAGE_NAME: haipham22/nginx-php-fpm

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build docker images
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          cache-from: ${{ env.IMAGE_NAME }}:8.1-fpm
          platforms: linux/amd64
          tags: |-
            ${{ env.IMAGE_NAME }}:latest
          build-args: PHP_FPM_VERSION=8.1-fpm-alpine

  buildx:
    needs: prepare
    strategy:
      matrix:
        php-version:
          [
            "7.3-fpm-alpine",
            "7.4-fpm-alpine",
            "8.0-fpm-alpine",
            "8.1-fpm-alpine",
            "8.2-fpm-alpine",
          ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          pull: true
          push: true
          cache-from: ${{ env.IMAGE_NAME }}:${{ matrix.php-version }}
          tags: |-
            ${{ env.IMAGE_NAME }}:${{ matrix.php-version }}
          build-args: PHP_FPM_VERSION=${{ matrix.php-version }}
